#pragma once

#include "CoreMinimal.h"
#include "GeometryScript/MeshPrimitiveFunctions.h"
#include "UObject/Object.h"

#include "PCGCreatePrimitiveSettingsBase.generated.h"

class UDynamicMesh;

/**
 * Base class for the inline, per-primitive-type option objects used by the CreatePrimitive PCG node.
 * Each subclass wraps exactly one Geometry Script primitive-creation function (see MeshPrimitiveFunctions.h),
 * exposing that function's parameters as UPROPERTYs and calling it directly - no primitive geometry is
 * generated by hand here.
 */
UCLASS(Abstract, EditInlineNew, DefaultToInstanced, CollapseCategories, BlueprintType)
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveSettingsBase : public UObject
{
	GENERATED_BODY()

public:
	/** Shared by every Geometry Script primitive function: PolyGroup mode, orientation, UV mode, and Material ID. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Primitive Options", meta = (ShowOnlyInnerProperties))
	FGeometryScriptPrimitiveOptions PrimitiveOptions;

	/** Appends this primitive to TargetMesh at Transform, via the corresponding Geometry Script primitive function. */
	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const
		PURE_VIRTUAL(UPCGCreatePrimitiveSettingsBase::AppendPrimitive,);
};

UCLASS(DisplayName = "Box")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveBoxSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Box", meta = (ClampMin = "0"))
	float DimensionX = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Box", meta = (ClampMin = "0"))
	float DimensionY = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Box", meta = (ClampMin = "0"))
	float DimensionZ = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Box", meta = (ClampMin = "0"))
	int32 StepsX = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Box", meta = (ClampMin = "0"))
	int32 StepsY = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Box", meta = (ClampMin = "0"))
	int32 StepsZ = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Box")
	EGeometryScriptPrimitiveOriginMode Origin = EGeometryScriptPrimitiveOriginMode::Base;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UENUM(BlueprintType)
enum class EPCGCreatePrimitiveSphereTopology : uint8
{
	/** UGeometryScriptLibrary_MeshPrimitiveFunctions::AppendSphereLatLong. */
	LatLong,
	/** UGeometryScriptLibrary_MeshPrimitiveFunctions::AppendSphereBox. */
	Box
};

UCLASS(DisplayName = "Sphere")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveSphereSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	/** Geometry Script exposes two sphere tessellations; LatLong is the classic latitude/longitude sphere, Box projects a subdivided cube. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere")
	EPCGCreatePrimitiveSphereTopology Topology = EPCGCreatePrimitiveSphereTopology::LatLong;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere", meta = (ClampMin = "0"))
	float Radius = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere", meta = (ClampMin = "2",
		EditCondition = "Topology==EPCGCreatePrimitiveSphereTopology::LatLong", EditConditionHides))
	int32 StepsPhi = 10;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere", meta = (ClampMin = "3",
		EditCondition = "Topology==EPCGCreatePrimitiveSphereTopology::LatLong", EditConditionHides))
	int32 StepsTheta = 16;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere", meta = (ClampMin = "1",
		EditCondition = "Topology==EPCGCreatePrimitiveSphereTopology::Box", EditConditionHides))
	int32 StepsX = 6;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere", meta = (ClampMin = "1",
		EditCondition = "Topology==EPCGCreatePrimitiveSphereTopology::Box", EditConditionHides))
	int32 StepsY = 6;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere", meta = (ClampMin = "1",
		EditCondition = "Topology==EPCGCreatePrimitiveSphereTopology::Box", EditConditionHides))
	int32 StepsZ = 6;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Sphere")
	EGeometryScriptPrimitiveOriginMode Origin = EGeometryScriptPrimitiveOriginMode::Center;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Capsule")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveCapsuleSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule", meta = (ClampMin = "0"))
	float Radius = 30.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule", meta = (ClampMin = "0"))
	float LineLength = 75.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule", meta = (ClampMin = "2"))
	int32 HemisphereSteps = 5;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule", meta = (ClampMin = "3"))
	int32 CircleSteps = 8;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule", meta = (ClampMin = "0"))
	int32 SegmentSteps = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Capsule")
	EGeometryScriptPrimitiveOriginMode Origin = EGeometryScriptPrimitiveOriginMode::Base;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Cylinder")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveCylinderSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cylinder", meta = (ClampMin = "0"))
	float Radius = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cylinder", meta = (ClampMin = "0"))
	float Height = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cylinder", meta = (ClampMin = "3"))
	int32 RadialSteps = 12;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cylinder", meta = (ClampMin = "0"))
	int32 HeightSteps = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cylinder")
	bool bCapped = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cylinder")
	EGeometryScriptPrimitiveOriginMode Origin = EGeometryScriptPrimitiveOriginMode::Base;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Cone")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveConeSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cone", meta = (ClampMin = "0"))
	float BaseRadius = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cone", meta = (ClampMin = "0"))
	float TopRadius = 5.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cone", meta = (ClampMin = "0"))
	float Height = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cone", meta = (ClampMin = "3"))
	int32 RadialSteps = 12;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cone", meta = (ClampMin = "0"))
	int32 HeightSteps = 4;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cone")
	bool bCapped = true;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cone")
	EGeometryScriptPrimitiveOriginMode Origin = EGeometryScriptPrimitiveOriginMode::Base;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Torus")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveTorusSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Torus", meta = (ClampMin = "0"))
	float MajorRadius = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Torus", meta = (ClampMin = "0"))
	float MinorRadius = 25.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Torus", meta = (ClampMin = "3"))
	int32 MajorSteps = 16;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Torus", meta = (ClampMin = "3"))
	int32 MinorSteps = 8;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Torus")
	EGeometryScriptPrimitiveOriginMode Origin = EGeometryScriptPrimitiveOriginMode::Base;

	/** Controls revolve angle/direction; RevolveDegrees < 360 produces a partial torus arc. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Torus", meta = (ShowOnlyInnerProperties))
	FGeometryScriptRevolveOptions RevolveOptions;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Rectangle")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveRectangleSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rectangle", meta = (ClampMin = "0"))
	float DimensionX = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rectangle", meta = (ClampMin = "0"))
	float DimensionY = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rectangle", meta = (ClampMin = "0"))
	int32 StepsWidth = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rectangle", meta = (ClampMin = "0"))
	int32 StepsHeight = 0;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Rounded Rectangle")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveRoundedRectangleSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rounded Rectangle", meta = (ClampMin = "0"))
	float DimensionX = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rounded Rectangle", meta = (ClampMin = "0"))
	float DimensionY = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rounded Rectangle", meta = (ClampMin = "0"))
	float CornerRadius = 5.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rounded Rectangle", meta = (ClampMin = "0"))
	int32 StepsWidth = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rounded Rectangle", meta = (ClampMin = "0"))
	int32 StepsHeight = 0;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Rounded Rectangle", meta = (ClampMin = "1"))
	int32 StepsRound = 4;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Disc")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveDiscSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Disc", meta = (ClampMin = "0"))
	float Radius = 50.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Disc", meta = (ClampMin = "3"))
	int32 AngleSteps = 16;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Disc", meta = (ClampMin = "0"))
	int32 SpokeSteps = 0;

	/** Degrees; StartAngle/EndAngle < full 360 range produces a partial disc/pie wedge. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Disc")
	float StartAngle = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Disc")
	float EndAngle = 360.0f;

	/** Radius of a central hole; produces a ring/annulus when greater than zero. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Disc", meta = (ClampMin = "0"))
	float HoleRadius = 0.0f;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Linear Stairs")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveLinearStairsSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Linear Stairs", meta = (ClampMin = "0"))
	float StepWidth = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Linear Stairs", meta = (ClampMin = "0"))
	float StepHeight = 20.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Linear Stairs", meta = (ClampMin = "0"))
	float StepDepth = 30.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Linear Stairs", meta = (ClampMin = "1"))
	int32 NumSteps = 8;

	/** If true, each step is a floating slab instead of a solid stacked staircase. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Linear Stairs")
	bool bFloating = false;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};

UCLASS(DisplayName = "Curved Stairs")
class PCGUTILSDYNMESH_API UPCGCreatePrimitiveCurvedStairsSettings : public UPCGCreatePrimitiveSettingsBase
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Curved Stairs", meta = (ClampMin = "0"))
	float StepWidth = 100.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Curved Stairs", meta = (ClampMin = "0"))
	float StepHeight = 20.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Curved Stairs", meta = (ClampMin = "0"))
	float InnerRadius = 150.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Curved Stairs")
	float CurveAngle = 90.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Curved Stairs", meta = (ClampMin = "1"))
	int32 NumSteps = 8;

	/** If true, each step is a floating slab instead of a solid stacked staircase. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Curved Stairs")
	bool bFloating = false;

	virtual void AppendPrimitive(UDynamicMesh* TargetMesh, const FTransform& Transform) const override;
};
